blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView


app_name = "blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create', BlogCreateView.as_view(), name="create"),
    path('detail/<int:pk>', BlogDetailView.as_view(), name="detail"),
    path('update/<int:pk>', BlogUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name="delete")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField(default="Some")

    def __str__(self):
        return self.title.upper()

    def getDetail(self):
        return f'Title: {self.title}\nContent: {self.content}'

    def getShortContent(self):
        return self.content if len(self.content) < 100 else f'{self.content[:150]}...'

    def getContent(self):
        return self.content

    def isContentShort(self):
        lenCaracteres = len(self.content)
        lenEspacios = self.content.count('\n')
        return True if not (lenEspacios >= 40 or (lenEspacios + lenCaracteres) >= 4930) else False

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import PostCreateForm
from .models import Post
import random
# Create your views here.


class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, 'blog_list.html', context)


class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            'form': form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):

        if request.method == 'POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(
                    title=title, content=content)
                p.save()
                return redirect('blog:home')

        context = {}
        return render(request, 'blog_create.html', context)


class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        posts = Post.objects.all()
        post = get_object_or_404(Post, pk=pk)
        postSelected = []
        if len(posts) > 4:
            for i in range(4):
                includePost = posts[random.randrange(0, len(posts) - 1)]
                while (includePost in postSelected or includePost == post):
                    includePost = posts[random.randrange(0, len(posts) - 1)]
                postSelected.append(includePost)

        context = {
            'post': post,
            'posts': postSelected
        }
        return render(request, 'blog_detail.html', context)


class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk': pk})


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post': post
        }
        return render(request, 'blog_delete.html', context)

core/views.py
from django.shortcuts import render
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }

        context = {

        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% tailwind_css %}
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Lobster&display=swap');
      .fondo {
        background-color: black;
      }
      h1, h2{
        font-family: 'Lobster', cursive;
      }
      }
    </style>
    <title>Document</title>
  </head>
  <body>
    <div class="fondo">
      <div class="container mx-auto px-5 py-5 bg-[#f1f5f9]">
        {% block content %}{% endblock content %}
      </div>
    </div>
  </body>
</html>

templates/blog_create.html
{%extends 'base.html'%} {% load crispy_forms_tags %} {% block content %}
<form class="h-full" method="POST">
  {% csrf_token %} {{form | crispy}}
  <button class="bg-green-500 px-5 py-3 rounded" type="submit">Crear</button>
</form>
{% endblock content %}

templates/blog_delete.html
<form method="POST">
  {% csrf_token %} Are you sure Delete {{post}} ?
  <button type="submit">Delete</button>
</form>

templates/blog_detail.html
{% extends 'base.html' %} {% block content %}
<div
  class="flex flex-col {% if post.isContentShort %}h-full{% endif %}"
>
  <div>
    <h1 class="text-[50px] w-full text-center">{{post}}</h1>
    <content class="px-10">{{post.getContent | linebreaks}}</content>
  </div>
  <hr class="border-4 border-black"/>
  <div class="grid grid-col-4 grid-flow-row">
    <h2 class="text-[20px] col-span-4">Tambien te podría interesar:</h2>
    {% for aux in posts %}
    <a href={% url 'blog:detail' aux.id %} class="mx-10 my-10 bg-black text-[#ffff] rounded-md border-2 drop-shadow-lg">
        <h2 class="py-5 text-center font-bold">{{aux.title}}</h2>
        <p class="px-5">{{aux.getShortContent}}</p>
      </a>
    {% endfor %}
  </div>
  <div class="flex">
    <div class="flex-auto text-center"><button><a class="bg-yellow-500 px-5 py-3 te rounded s" href= {% url 'blog:update' post.id%}>Editar Post</a></button></div>
    <div class="flex-auto text-center"><button><a class="bg-red-500 px-5 py-3 te rounded s" href= {% url 'blog:delete' post.id%}>Eliminar Post</a></button></div>
    <div class="flex-auto text-center"><button><a class="bg-green-500 px-5 py-3 te rounded s" href= {% url 'blog:home'%}>Regresar al home</a></button></div>
  </div>
</div>

{% endblock content %}

templates/blog_list.html
{% extends 'base.html' %} {% block content %}
<div class="grid grid-cols-3 justify-between">
  <h1 class="col-span-3 text-center text-[100px] font-bold">FILOSOFIA DE VIDA</h1>
    {% for post in posts %}
    <a href={% url 'blog:detail' post.id %} class="mx-10 my-10 bg-black text-[#ffff] rounded-md border-2 drop-shadow-lg">
      <h2 class="py-5 text-center font-bold">{{post.title}}</h2>
      <p class="px-5">{{post.getShortContent}}</p>
    </a>
    {% endfor %}
    
  <div class="col-span-3 self-end justify-self-center"><button><a class="bg-green-500 px-5 py-3 te rounded" href= {% url 'blog:create' %}>Nuevo Post</a></button></div>
</div>

{% endblock content %}

templates/blog_update.html
{%extends 'base.html'%} {% load crispy_forms_tags %} {% block content %}
<form class="h-full" method="POST">
  {% csrf_token %} {{form | crispy}}
  <button class="bg-green-500 px-5 py-3 rounded" type="submit">
    Actualizar
  </button>
</form>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<html lang="en">
  <head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% tailwind_css %}
  </head>

  <body class="bg-grey-lightest font-serif leading-normal tracking-normal">
    <div class="container mx-auto">
      <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
      </section>
    </div>
  </body>
</html>